var galleryItems = [
  {
  "src": "images/suspiria_54003490783_o.png",
  "title": "Suspiria",
  "description": "I recently watched the film <a href=\"https://letterboxd.com/film/suspiria/\">Suspiria (1977)</a>, which has this interesting floor pattern. I've recreated that in this image.",
  "date": "2024-09-18",
  "tags": "csharp suspiria film_and_tv",
  "enabled": true,
},
  {
  "src": "images/daisies_53914211551_o.png",
  "title": "Daisies",
  "description": "Whilst watching the film <a href=\"https://letterboxd.com/film/daisies/\">Daisies (1966)</a> I saw this poster in the background and had a go at recreating it.<br>The &quot;K&quot; is from freestencilletters.com",
  "date": "2024-08-10",
  "tags": "inkscape daisies studio_balet_praha kontrasty black_and_white film_and_tv",
  "enabled": true,
},
  {
  "src": "images/bound_53884641294_o.png",
  "title": "Bound",
  "description": "I recently watched the film <a href=\"https://letterboxd.com/film/bound/\">Bound (1996)</a>, which has prominent circle art on a drinks cabinet featured throughout the film. I've recreated that in this image.",
  "date": "2024-07-27",
  "tags": "inkscape bound circles black_and_white film_and_tv",
  "enabled": true,
},
  {
  "src": "images/osterried-71_53826038239_o.png",
  "title": "Osterried 71",
  "description": "Whilst watching the film <a href=\"https://letterboxd.com/film/all-of-us-strangers/\">All of Us Strangers (2023)</a> I noticed a picture in the background of the protagonist's flat. I wanted to find that, but no amount of Googling was leading to any answers. I came to the conclusion that it doesn't exist outside of the film, so I recreated it and that's the image above. The picture is always shown in shadow, darkness, and/or far away, so I'm not certain about the colours or the letters.",
  "date": "2024-06-30",
  "tags": "javascript all_of_us_strangers osterried_71 film_and_tv black_and_white",
  "enabled": true,
},
  {
  "src": "images/bauhaus-pattern-2_53465564948_o.png",
  "title": "Bauhaus Pattern #2",
  "description": "An example output from my <a href=\"https://robson.plus/bauhaus-pattern-creator/\">Bauhaus Pattern Creator</a>.",
  "date": "2024-01-15",
  "tags": "random bauhaus pattern javascript",
  "enabled": true,
},
  {
  "src": "images/bauhaus-pattern-1_53465564963_o.png",
  "title": "Bauhaus Pattern #1",
  "description": "An example output from my <a href=\"https://robson.plus/bauhaus-pattern-creator/\">Bauhaus Pattern Creator</a>.",
  "date": "2024-01-15",
  "tags": "random bauhaus pattern javascript black_and_white",
  "enabled": true,
},
  {
  "src": "images/optical-illusion-the-red-lines-are-of-equal-height_50764244973_o.png",
  "title": "Optical Illusion",
  "description": "The red lines are of equal height. This is a <a href=\"https://en.wikipedia.org/wiki/Ponzo_illusion\">Ponzo illusion</a>.",
  "date": "2020-12-27",
  "tags": "illusion inkscape",
  "enabled": true,
},
  {
  "src": "images/spiral-maze_50193579767_o.png",
  "title": "Spiral Maze",
  "description": "This is heavily biased towards turning right, so that it creates a messy spiral pattern in the middle.",
  "date": "2020-08-05",
  "tags": "csharp random maze black_and_white",
  "enabled": true,
},
  {
  "src": "images/impossible-geometry---isometric_50175158666_o.png",
  "title": "Impossible Geometry - Isometric",
  "description": "",
  "date": "2020-08-01",
  "tags": "csharp black_and_white impossible_geometry 3d",
  "enabled": true,
},
  {
  "src": "images/impossible-geometry---flat_50152177351_o.png",
  "title": "Impossible Geometry - Flat",
  "description": "",
  "date": "2020-07-25",
  "tags": "black_and_white random csharp impossible_geometry 3d",
  "enabled": true,
},
  {
  "src": "images/glitch_50094455547_o.png",
  "title": "Glitch",
  "description": "I made a tool for generating glitched images: <a href=\"https://github.com/Robson/Glitch-Generator\">Glitch Generator</a>.",
  "date": "2020-07-09",
  "tags": "random csharp glitch",
  "enabled": true,
},
  {
  "src": "images/every-colour-in-ulysses_49870543078_o.png",
  "title": "Every Colour in Ulysses",
  "description": "Every colour in <a href=\"https://en.wikipedia.org/wiki/Ulysses_(novel)\">Ulysses</a> by James Joyce.",
  "date": "2020-05-08",
  "tags": "csharp javascript text ulysses",
  "enabled": true,
},
  {
  "src": "images/abelian-sandpile-uniform_49767200211_o.png",
  "title": "Abelian Sandpile: Uniform",
  "description": "<a href=\"https://en.wikipedia.org/wiki/Abelian_sandpile_model\">Abelian sandpile model</a>. The initial state of this is a 304x304 grid, with every space containing a sandpile of 4 grains.",
  "date": "2020-04-13",
  "tags": "csharp black_and_white abelian_sandpile fractal",
  "enabled": true,
},
  {
  "src": "images/wren-and-me_49758496271_o.png",
  "title": "Wren and Me",
  "description": "I was watching the TV show <em>Moon and Me</em> with my niece, which has a short sequence with an animated version of the moon.<br>I liked their depiction so much that I wrote some JavaScript that randomly creates the same thing. This is a screenshot from that.",
  "date": "2020-04-10",
  "tags": "random javascript jquery moon film_and_tv",
  "enabled": true,
},
  {
  "src": "images/maurer-roses_48914670778_o.png",
  "title": "Maurer Roses",
  "description": "<a href=\"https://en.wikipedia.org/wiki/Maurer_rose\">Maurer Rose</a>.",
  "date": "2019-10-17",
  "tags": "black_and_white javascript random maurer maurer_rose",
  "enabled": true,
},
  {
  "src": "images/garden-xylophone_48447712876_o.png",
  "title": "Garden Xylophone",
  "description": "I wrote a random generator that makes pictures in the style of <a href=\"https://en.wikipedia.org/wiki/Terry_Frost\">Sir Terry Frost's</a> painting &quot;Orchard Tambourine&quot;.",
  "date": "2019-08-03",
  "tags": "csharp random colour terry_frost",
  "enabled": true,
},
  {
  "src": "images/video-letter-frequency_32419745947_o.png",
  "title": "Video: Letter Frequency",
  "description": "<a href=\"https://www.youtube.com/watch?v=zJvdGDODOlY\">Watch it here</a>.<br>This animation shows the letter frequency for the central part of John F. Kennedy's speech: &quot;We choose to go to the Moon&quot;.",
  "date": "2019-03-12",
  "tags": "letter frequency jquery javascript video text",
  "enabled": true,
},
  {
  "src": "images/video-rotating-circles_32419746007_o.png",
  "title": "Video: Rotating Circles",
  "description": "<a href=\"https://www.youtube.com/watch?v=men-7bsLPPk\">Watch it here</a>.",
  "date": "2019-03-12",
  "tags": "video javascript p5js circles",
  "enabled": true,
},
  {
  "src": "images/video-warehouse-simulation_47309055582_o.png",
  "title": "Video: Warehouse Simulation",
  "description": "<a href=\"https://www.youtube.com/watch?v=GhGxoXBSmfI\">Watch it here</a>.<br>I've always found the Amazon warehouse robots to be an interesting system, so I thought it would be fun to make my own basic version.<br>The idea here is that letters arrive on the left, get moved into the warehouse in the middle, then get output on the right.",
  "date": "2019-03-12",
  "tags": "warehouse random simulation video csharp text",
  "enabled": true,
},
  {
  "src": "images/space_46477048644_o.png",
  "title": "Space",
  "description": "I combined unicode characters and emojis to make a <a href=\"https://robson.plus/space-generator/\">random space generator</a>.",
  "date": "2019-02-24",
  "tags": "jquery javascript random space",
  "enabled": true,
},
  {
  "src": "images/trapped-knight_46875184141_o.png",
  "title": "Trapped Knight",
  "description": "I saw the recent Numberphile video on <a href=\"https://www.youtube.com/watch?v=RGQe8waGJ4w\">The Trapped Knight</a> and then wrote my own visualisation of this.",
  "date": "2019-01-25",
  "tags": "csharp colour trapped_knight",
  "enabled": true,
},
  {
  "src": "images/recamn-sequence-zoomed_29242379898_o.png",
  "title": "Recamán Sequence (Zoomed)",
  "description": "A cropped visualisation of the start of the Recamán sequence, which is heavily inspired by <a href=\"https://www.youtube.com/watch?v=FGC5TdIiT9U\">this Numberphile video</a>. The video also contains a full explanation of the sequence.",
  "date": "2018-06-30",
  "tags": "black_and_white csharp Recamán",
  "enabled": true,
},
  {
  "src": "images/recamn-sequence_42209946215_o.png",
  "title": "Recamán Sequence",
  "description": "A visualisation of the first 33 steps in the Recamán sequence, which is heavily inspired by <a href=\"https://www.youtube.com/watch?v=FGC5TdIiT9U\">this Numberphile video</a>. The video also contains a full explanation of the sequence.",
  "date": "2018-06-30",
  "tags": "black_and_white Recamán csharp",
  "enabled": true,
},
  {
  "src": "images/kolakoski-sequence_42395342864_o.png",
  "title": "Kolakoski Sequence",
  "description": "A visualisation of the <a href=\"https://en.wikipedia.org/wiki/Kolakoski_sequence\">Kolakoski sequence</a> based on the one found in <a href=\"https://www.youtube.com/watch?v=co5sOgZ3XcM\">this Numberphile video</a>.<br>The left-side is with grey lines to denote the individual segments, whilst the right-side is without the grey lines.",
  "date": "2018-06-30",
  "tags": "black_and_white csharp kolakoski fractal",
  "enabled": true,
},
  {
  "src": "images/collatz-conjecture_42101242924_o.png",
  "title": "Collatz Conjecture",
  "description": "This visualisation of the Collatz conjecture is completely based on this Reddit post by bertnor:<br><a href=\"https://www.reddit.com/r/dataisbeautiful/comments/8miru1/a_graph_of_the_collatz_conjecture_how_the_first/\">www.reddit.com/r/dataisbeautiful/comments/8miru1/a_graph_...</a><br>The image shows the paths of the first 10,000 numbers.<br>An explanation of the Collatz conjecture can be found here:<br><a href=\"https://www.youtube.com/watch?v=5mFpVDpKX70\">www.youtube.com/watch?v=5mFpVDpKX70</a>",
  "date": "2018-06-15",
  "tags": "black_and_white csharp collatz_conjecture",
  "enabled": false,
},
  {
  "src": "images/elementary-cellular-automaton_34546517700_o.png",
  "title": "Elementary Cellular Automaton",
  "description": "",
  "date": "2017-05-28",
  "tags": "black_and_white random csharp Cellular_Automaton",
  "enabled": true,
},
  {
  "src": "images/lissajous-curve_33267635512_o.png",
  "title": "Lissajous Curve",
  "description": "5:6",
  "date": "2017-03-13",
  "tags": "Lissajous_Curve Lissajous curve csharp",
  "enabled": true,
},
  {
  "src": "images/notable-world_29060306850_o.png",
  "title": "Notable World",
  "description": "This is the location of the subject of every Wikipedia article (if it has a location).",
  "date": "2016-08-30",
  "tags": "black_and_white wikipedia map",
  "enabled": true,
},
  {
  "src": "images/idioms_20174926813_o.png",
  "title": "Idioms",
  "description": "",
  "date": "2015-08-22",
  "tags": "inkscape black_and_white text",
  "enabled": true,
},
  {
  "src": "images/awful-wordsearch-level_20499138671_o.png",
  "title": "Awful Wordsearch: Level",
  "description": "",
  "date": "2015-08-11",
  "tags": "black_and_white text random wordsearch csharp",
  "enabled": true,
},
  {
  "src": "images/voronoi-fox_20110272152_o.png",
  "title": "Voronoi Fox",
  "description": "Inspired by the <a href=\"https://www.reddit.com/r/mathpics/comments/3ewwbi/image_voronoi_tessellation_ochowto_in_comments/\">image voronoi tesselation</a> post on Reddit.<br>Original image from <a href=\"http://wall.alphacoders.com/big.php?i=433741\">wall.alphacoders.com/big.php?i=433741</a>",
  "date": "2015-07-29",
  "tags": "csharp random fox voronoi",
  "enabled": false,
},
  {
  "src": "images/happy-tau-day_19217312495_o.png",
  "title": "Happy Tau Day!",
  "description": "Tau day is exactly twice as awesome as Pi day.",
  "date": "2015-06-28",
  "tags": "csharp black_and_white random tau",
  "enabled": true,
},
  {
  "src": "images/clock-word_18516899332_o.png",
  "title": "Clock Word",
  "description": "View the <a href=\"http://iceyboard.no-ip.org/wordclock/\">live version</a>.<br>This was inspired by Reddit user <a href=\"http://www.reddit.com/user/buckeyeworldcitizen\">buckeyeworldcitizen</a>'s invention: <a href=\"http://imgur.com/a/iMXmj\">Birthday Word Clock</a>.",
  "date": "2015-06-06",
  "tags": "javascript jquery clock time text",
  "enabled": false,
},
  {
  "src": "images/overlook-hotel-carpet_15682295092_o.png",
  "title": "Overlook Hotel Carpet",
  "description": "",
  "date": "2014-11-01",
  "tags": "Processing processorg pattern the_shining overlook_hotel carpet film_and_tv",
  "enabled": true,
},
  {
  "src": "images/butterfly_14622457526_o.png",
  "title": "Butterfly",
  "description": "Learning how to make vector art. This butterfly was created by following this tutorial: <a href=\"http://design.tutsplus.com/tutorials/how-to-make-an-attractive-vector-butterfly--vector-3415\">design.tutsplus.com/tutorials/how-to-make-an-attractive-v...</a>",
  "date": "2014-07-13",
  "tags": "inkscape vector butterfly 3d",
  "enabled": false,
},
  {
  "src": "images/spinning_14492060954_o.png",
  "title": "Spinning",
  "description": "",
  "date": "2014-06-24",
  "tags": "Processing processingorg colour random",
  "enabled": true,
},
  {
  "src": "images/peggy_14206866909_o.png",
  "title": "Peggy",
  "description": "Each of Peggy's office outfits from the latest season of Mad Men.",
  "date": "2014-06-10",
  "tags": "Processing processingorg peggy mad_men film_and_tv",
  "enabled": true,
},
  {
  "src": "images/50-squares-of-grey_14316399736_o.png",
  "title": "50 Squares of Grey",
  "description": "A interpretation of Vera Molnar's art &quot;25 Squares&quot;, built as a randomly generating Processing sketch. The pencil effect is achieved by using the <a href=\"http://www.gicentre.net/handy/\">Handy library</a>.<br>p.s. There's only 49 squares. I'm a liar.",
  "date": "2014-06-03",
  "tags": "Processing processingorg random vera_molnar 25_squares black_and_white",
  "enabled": false,
},
  {
  "src": "images/25-squares_14337757042_o.png",
  "title": "25 Squares",
  "description": "A recreation of Vera Molnar's art &quot;25 Squares&quot;, built as a randomly generating Processing sketch.",
  "date": "2014-06-03",
  "tags": "Processing processingorg random 25_squares vera_molnar",
  "enabled": false,
},
  {
  "src": "images/alhambra_14321950304_o.png",
  "title": "Alhambra",
  "description": "",
  "date": "2014-06-01",
  "tags": "Processing processingorg random alhambra",
  "enabled": true,
},
  {
  "src": "images/think-inside-the-box_14233074054_o.png",
  "title": null,
  "description": "",
  "date": "2014-05-20",
  "tags": "Processing processingorg fractal 3d",
  "enabled": true,
},
  {
  "src": "images/colourfall_14207891745_o.png",
  "title": "Colourfall",
  "description": "This is every 24-bit colour, exactly once. That's 16,777,216 colours.",
  "date": "2014-05-17",
  "tags": "csharp colour random",
  "enabled": true,
},
  {
  "src": "images/true-colours_14205718035_o.png",
  "title": "True Colours",
  "description": "This is every 24-bit colour, exactly once. That's 16,777,216 colours.<br>My first go at writing the code for this was going to take about 210 days to complete, but with some optimisation I got that down to 15 hours.",
  "date": "2014-05-17",
  "tags": "csharp colour random",
  "enabled": true,
},
  {
  "src": "images/pinwheel-fractal_14008432918_o.png",
  "title": "Pinwheel Fractal",
  "description": "<a href=\"http://en.wikipedia.org/wiki/Pinwheel_tiling\">Pinwheel tiling</a>.",
  "date": "2014-05-16",
  "tags": "Processing processingorg black_and_white fractal",
  "enabled": true,
},
  {
  "src": "images/snow_13986039780_o.png",
  "title": "Snow",
  "description": "",
  "date": "2014-05-12",
  "tags": "Processing processingorg random black_and_white snow",
  "enabled": true,
},
  {
  "src": "images/erosion_14113646842_o.png",
  "title": "Conception",
  "description": "Conway's game of life inside Conway's game of life.",
  "date": "2014-05-05",
  "tags": "Processing processingorg black_and_white random game_of_life conway",
  "enabled": true,
},
  {
  "src": "images/patterns_13787464413_o.png",
  "title": "Monochrome Patterns",
  "description": "",
  "date": "2014-04-12",
  "tags": "csharp fractal black_and_white",
  "enabled": true,
},
  {
  "src": "images/colour-patterns_13787782934_o.png",
  "title": "Colour Patterns",
  "description": "",
  "date": "2014-04-12",
  "tags": "csharp fractal",
  "enabled": true,
},
  {
  "src": "images/3-weeks_13654965774_o.png",
  "title": "Cogs",
  "description": "",
  "date": "2014-04-06",
  "tags": "csharp random black_and_white",
  "enabled": true,
},
  {
  "src": "images/a-man-of-his-words_13678860513_o.png",
  "title": "A Man of His Words",
  "description": "",
  "date": "2014-04-06",
  "tags": "Processing processingorg text random michael_jackson black_and_white",
  "enabled": true,
},
  {
  "src": "images/films_12621742244_o.png",
  "title": "Films",
  "description": "Playing with fading, saturation, blurring, corruption, textures, perlin noise, font sizing...",
  "date": "2014-02-18",
  "tags": "Processing processingorg random text film_and_tv",
  "enabled": false,
},
  {
  "src": "images/autostereogram_12548983274_o.png",
  "title": "Autostereogram",
  "description": "It's one of those magic-eye pictures.",
  "date": "2014-02-15",
  "tags": "Processing processingorg random autostereogram",
  "enabled": true,
},
  {
  "src": "images/heat-signature-spaceships_12391738953_o.png",
  "title": "Heat Signature Spaceships",
  "description": "<a href=\"http://www.pentadact.com\">Tom Francis</a> is writing a game called <a href=\"http://www.pentadact.com/tag/heat-signature/\">Heat Signature</a>, which has randomly generated spaceships.<br>He recently posted the <a href=\"http://www.pentadact.com/2014-02-07-randomly-generating-simple-spaceships-in-heat-signature/\">rules for generating spaceships</a>, so I translated those rules into Processing code and generated this image.",
  "date": "2014-02-08",
  "tags": "Processing processingorg random heat_signature tom_francis",
  "enabled": true,
},
  {
  "src": "images/whisky-recommendr_12195438913_o.png",
  "title": "Whisky Recommendr",
  "description": "I found some <a href=\"https://www.mathstat.strath.ac.uk/outreach/nessie/nessie_whisky.html\">interesting whisky data</a>  and wanted to turn it into an interactive recommendation tool.<br>This was written using d3.js<br>Play with it here:<br><a href=\"http://iceyboard.no-ip.org/whisky_recommendr/\">iceyboard.no-ip.org/whisky_recommendr/</a>",
  "date": "2014-01-28",
  "tags": "d3js chart interactive",
  "enabled": false,
},
  {
  "src": "images/imdb-tv-ratings_11895352126_o.png",
  "title": "IMDb TV Ratings",
  "description": "More playing around with <a href=\"http://nvd3.org/\">NVD3</a> and <a href=\"http://d3js.org/\">D3JS</a>.<br>Sadly, the IMDb doesn't provide an API, so I had to scrape all of the data using C# to make the preset list. Hopefully that will change in the future.<br>Play with it here:<br><a href=\"http://iceyboard.no-ip.org/imdb_tv_ratings/1/\">iceyboard.no-ip.org/imdb_tv_ratings/1/</a>",
  "date": "2014-01-11",
  "tags": "d3.js nvd3 chart colour nvd3.js interactive film_and_tv",
  "enabled": false,
},
  {
  "src": "images/z-is-for-zeta-maze_11497272485_o.png",
  "title": "Zeta Maze",
  "description": "A zeta maze has paths at 45 degree angles, as well as the usual 90 degree angles.",
  "date": "2013-12-22",
  "tags": "Processing processingorg maze random black_and_white",
  "enabled": true,
},
  {
  "src": "images/zeta-maze-alternative_11497465045_o.png",
  "title": "Zeta Maze (Alternative)",
  "description": "",
  "date": "2013-12-22",
  "tags": "Processing processingorg maze random black_and_white",
  "enabled": false,
},
  {
  "src": "images/background_11260505266_o.png",
  "title": "Background",
  "description": "On the web and the TV, I sometimes see images with faded and blurry backgrounds. I wanted to write a Processing sketch that created a similar effect.<br>This was achieved by averaging the colours, lightening them, mapping them to a wider area and applying a subtle texture to make them appear a little &quot;grainy&quot;.",
  "date": "2013-12-08",
  "tags": "Processing processingorg",
  "enabled": false,
},
  {
  "src": "images/y-is-for-year-of-formula-1_11269670565_o.png",
  "title": "Y is for Year of Formula 1",
  "description": "<a href=\"http://iceyboard.no-ip.org/f1/2013/\">Formula 1 Statistics, 2013</a><br>I've been learning Javascript, d3.js and NVD3, so that I can make elegant web pages of interactive charts. The link above is my first project.",
  "date": "2013-12-08",
  "tags": "d3.js nvd3 nvd3.js interactive chart colour",
  "enabled": false,
},
  {
  "src": "images/poincar-disc_10893685965_o.png",
  "title": "Poincaré Disc",
  "description": "",
  "date": "2013-11-16",
  "tags": "black_and_white csharp fractal",
  "enabled": true,
},
  {
  "src": "images/tileable-circuit---large_10637024076_o.png",
  "title": "Tileable Circuit - Large",
  "description": "",
  "date": "2013-11-03",
  "tags": "black_and_white random Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/tileable-circuit---small_10637249373_o.png",
  "title": "Tileable Circuit - Small",
  "description": "",
  "date": "2013-11-03",
  "tags": "black_and_white random proc Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/shine-grey-like-a-diamond_10298336504_o.png",
  "title": "Optical Illusion",
  "description": "All the diamonds are the same.",
  "date": "2013-10-15",
  "tags": "illusion black_and_white Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/piet-mondrian-generator_9972796593_o.png",
  "title": "Piet Mondrian Generator",
  "description": "Decided to improve my <a href=\"http://en.wikipedia.org/wiki/Piet_Mondrian\">Mondrian</a>-style generator by rewriting it in C#, tweaking the algorithm and applying a texture afterwards.",
  "date": "2013-09-27",
  "tags": "piet_mondrian random csharp",
  "enabled": true,
},
  {
  "src": "images/x-is-for-xmas_9741219579_o.png",
  "title": "X is for Xmas",
  "description": "<a href=\"http://farm8.staticflickr.com/7341/9741219579_25da07df06_o.png\">Original Size</a>.",
  "date": "2013-09-14",
  "tags": "excel chart text",
  "enabled": false,
},
  {
  "src": "images/minesweeper-heatmap_9689614290_o.png",
  "title": "Minesweeper Heatmap",
  "description": "Imagine this is the Intermediate board on classic Minesweeper (16x16 with 40 mines).<br>On your first click a number of tiles are revealed. I wanted to know the average amount of tiles revealed for each starting tile. I simulated 100,000 games per tile and disregarded any that ended in instant failure.<br>The image shows the tiles that reveal the most on average (white) down to the tiles that reveal the least on average (black). The range is 18.26 tiles to 9.57 tiles.<br>My advice is to click one of the tiles on the center of an edge.",
  "date": "2013-09-06",
  "tags": "Processing processingorg csharp minesweeper black_and_white",
  "enabled": false,
},
  {
  "src": "images/w-is-for-walter-white_9629544395_o.png",
  "title": "Walter White",
  "description": "I keep noticing film and television characters that have colours in their names, especially since I started watching Breaking Bad.<br>I wanted to know if character names contained colours more frequently than real names. So I scrapped over 10,000 films and television episodes from Rotten Tomatoes and then analysed the names. The chart above is the result.<br>I excluded red from the chart, because almost all of the names containing &quot;Red&quot; weren't referring to the colour. For example, there were lots of people called Fred, Meredith and Mildred.",
  "date": "2013-08-30",
  "tags": "Processing processingorg csharp colour chart film_and_tv",
  "enabled": true,
},
  {
  "src": "images/v-is-for-videos_9584838270_o.png",
  "title": "V is for Videos",
  "description": "<a href=\"http://farm8.staticflickr.com/7331/9584838270_5773067dc2_o.png\">Original Size</a>.<br>I made this by extracting the frames at 10 second intervals using C#. Then I wrote a Processing sketch to determine the overall colour of each frame and draw it as lines.<br>I did this for 26 films that I thought would be interesting. The most interesting 13 made it into this graphic.",
  "date": "2013-08-24",
  "tags": "Processing processingorg csharp chart film_and_tv",
  "enabled": false,
},
  {
  "src": "images/cube_9585362502_o.png",
  "title": "Cube",
  "description": "This started as 32,000 filled cubes (the bottom half) and 32,000 empty cubes (the top half).<br>Cubes are then repeatedly added and removed, on the condition that they wouldn't create holes/breaks in the structure.<br>This is the result after approximately 13 hours.",
  "date": "2013-08-24",
  "tags": "Processing processingorg random 3d",
  "enabled": true,
},
  {
  "src": "images/u-is-for-uk-number-one-singles_9566073364_o.png",
  "title": "UK Number One Singles",
  "description": "My manager had the recent conjecture that songs stayed at number one for less time nowadays, compared to decades gone by.<br>I decided to find out, so I scrapped all of the data from Wikipedia, going back to the first number one.<br>The width of each segment shows how long each song stayed at number one. For example, the first song stayed at the top of the chart for 9 weeks.<br>The chart clearly shows that he was correct, because singles do change more frequently nowadays.",
  "date": "2013-08-21",
  "tags": "Processing processingorg csharp black_and_white music chart",
  "enabled": true,
},
  {
  "src": "images/t-is-for-tangled_9476213626_o.png",
  "title": "Tangled",
  "description": "The top row represents the amount of words that begin with that letter.<br>Then up to 26 lines travel down, based on the frequency of the second letter. For example, words beginning with C have O as the most common second letter.<br>The words are taken from a dictionary of 117,977 English words.",
  "date": "2013-08-10",
  "tags": "Processing processingorg csharp colour chart text",
  "enabled": true,
},
  {
  "src": "images/q-is-for-quarters_9411713316_o.gif",
  "title": "Animation: Twin Dragon Curve Fractal",
  "description": "",
  "date": "2013-07-31",
  "tags": "Processing processingorg dragon_curve gif animation colour fractal csharp",
  "enabled": true,
},
  {
  "src": "images/r-is-for-route_9411840488_o.png",
  "title": "Hexagon Maze (Small)",
  "description": "The coloured line shows the route from the start to the middle. The hexagon rooms get lighter as they move further away from the solution.",
  "date": "2013-07-31",
  "tags": "csharp colour maze random",
  "enabled": true,
},
  {
  "src": "images/massive-hexagon-maze_9411861834_o.png",
  "title": "Hexagon Maze (Large)",
  "description": "The coloured line shows the route from the start to the middle. The hexagon rooms get lighter as they move further away from the solution.",
  "date": "2013-07-31",
  "tags": "colour random maze csharp",
  "enabled": true,
},
  {
  "src": "images/s-is-for-segments_9411862584_o.png",
  "title": "Segments",
  "description": "",
  "date": "2013-07-31",
  "tags": "Processing processingorg black_and_white fractal",
  "enabled": true,
},
  {
  "src": "images/p-is-for-prime-spirals_9273328758_o.png",
  "title": "Prime Spirals",
  "description": "Each circle has 10,000 dots. The prime numbers are shown in white. The other circles are sized according to the number of divisors that they have, with more divisors being bigger circles.<br>The circle on the left is a <a href=\"http://en.wikipedia.org/wiki/Phyllotaxis\">Phyllotaxis</a> Spiral, using packing based on the Golden Ratio.<br>The circle on the right is a <a href=\"http://en.wikipedia.org/wiki/Ulam_spiral\">Ulam Spiral</a>, where the numbers are plotted on an <a href=\"http://en.wikipedia.org/wiki/Archimedean_spiral\">Archimedean Spiral</a>.",
  "date": "2013-07-13",
  "tags": "Processing processingorg black_and_white prime",
  "enabled": true,
},
  {
  "src": "images/o-is-for-optical-illusion_9226946398_o.png",
  "title": "Optical Illusion",
  "description": "The &quot;blue&quot; lines are the same colour as the &quot;green&quot; lines.",
  "date": "2013-07-06",
  "tags": "Processing processingorg colour illusion",
  "enabled": true,
},
  {
  "src": "images/k-is-for-king_9159320155_o.png",
  "title": "K is for King",
  "description": "Experimenting with maps! This map shows all of the McDonalds (red) and Burger Kings (black) in Warwickshire and the surrounding area.<br>The map is from Wikipedia:<br><a href=\"http://en.wikipedia.org/wiki/File:Warwickshire_UK_location_map.svg\">en.wikipedia.org/wiki/File:Warwickshire_UK_location_map.svg</a><br>McDonalds location data is from their SatNav data:<br><a href=\"http://www.mcdonalds.co.uk/ukhome/Restaurants/McDonaldssatnav.html\">www.mcdonalds.co.uk/ukhome/Restaurants/McDonaldssatnav.html</a><br>Burger King location data is from Pocket GPS World:<br><a href=\"http://www.pocketgpsworld.com/modules.php?name=POIs\">www.pocketgpsworld.com/modules.php?name=POIs</a>",
  "date": "2013-06-28",
  "tags": "Processing processingorg map",
  "enabled": false,
},
  {
  "src": "images/m-is-for-main-characters_9160334833_o.png",
  "title": "Main Characters",
  "description": "This shows the most frequently mentioned characters in the <em>Lord of the Rings</em> books. The horizontal distance is proportional to the amount of mentions.<br>Before and after each character you can see the most frequent words that appear before and after that character's name in the books. The vertical distance is proportional to the amount of mentions.",
  "date": "2013-06-28",
  "tags": "Processing processingorg text chart csharp colour",
  "enabled": true,
},
  {
  "src": "images/l-is-for-latitude-and-longitude_9162302052_o.png",
  "title": "L is for Latitude and Longitude",
  "description": "My manager has the ability to consistently select the most unhygienic places to order our takeaways from. A fact that is made more worrying by menu choices that are simply described as &quot;meat&quot;. One time he enquired as to the type of meat and was told &quot;It's just meat&quot;. He ordered it anyway.<br>The Food Standards Agency kindly provides food hygiene ratings for thousands of places around England, Wales and Northern Ireland. The ratings are from 1 (major improvement necessary) to 5 (very good).<br>I wanted to find out where the best and worst places were. So I scraped all of the files from here:<br><a href=\"http://ratings.food.gov.uk/open-data/en-GB\">ratings.food.gov.uk/open-data/en-GB</a><br>I determined the average for each location and plotted it on the map above. I made the London circles a bit smaller, because it was rather crowded. The map is courtesy of Wikipedia and is located here:<br><a href=\"http://commons.wikimedia.org/wiki/File:Uk-map.svg\">commons.wikimedia.org/wiki/File:Uk-map.svg</a><br>The five worst places on average are:<br>3.06 - London &gt; Sutton<br>3.09 - London &gt; Bexley<br>3.13 - London &gt; Hackney<br>3.30 - London &gt; Ealing<br>3.30 - London &gt; Lewisham<br>The five best places on average are:<br>4.67 - South West &gt; Mid Devon<br>4.70 - South East &gt; Tunbridge Wells<br>4.72 - South West &gt; South Gloucestershire<br>4.75 - North West &gt; Eden<br>4.79 - South West &gt; North Devon",
  "date": "2013-06-28",
  "tags": "Processing processingorg colour map csharp food",
  "enabled": false,
},
  {
  "src": "images/i-is-for-iterations_9052738161_o.png",
  "title": "Pythagoras Triangle Fractal",
  "description": "",
  "date": "2013-06-16",
  "tags": "Processing processingorg fractal black_and_white recursion",
  "enabled": true,
},
  {
  "src": "images/g-is-for-gosper-curve_8988559455_o.png",
  "title": "Gosper Curve",
  "description": "This is a level 5 left <a href=\"http://en.wikipedia.org/wiki/Gosper_curve\">Gosper curve</a>.",
  "date": "2013-06-08",
  "tags": "Processing processingorg colour gosper_curve recursion fractal",
  "enabled": true,
},
  {
  "src": "images/maze-alternative-angle_8988650751_o.png",
  "title": "Hallways #2",
  "description": "",
  "date": "2013-06-08",
  "tags": "Processing processingorg black_and_white random maze 3d",
  "enabled": true,
},
  {
  "src": "images/h-is-for-hallways_8989805984_o.png",
  "title": "Hallways #1",
  "description": "",
  "date": "2013-06-08",
  "tags": "Processing processingorg maze 3d black_and_white random",
  "enabled": true,
},
  {
  "src": "images/f-is-for-fractal_8952213840_o.png",
  "title": "Sierpiński Pyramid",
  "description": "<a href=\"https://en.wikipedia.org/wiki/Sierpi%C5%84ski_triangle\">Sierpiński triangle</a>.",
  "date": "2013-06-04",
  "tags": "Processing processingorg 3d triangle recursion black_and_white fractal",
  "enabled": true,
},
  {
  "src": "images/e-is-for-even_8907754286_o.png",
  "title": "Word Tree",
  "description": "I wrote a Processing sketch to generate these word trees.<br>The text is every sentence from Dexter  that starts with &quot;even&quot;.",
  "date": "2013-06-01",
  "tags": "csharp text word_tree black_and_white film_and_tv",
  "enabled": true,
},
  {
  "src": "images/dragon-curve-pattern_8842614968_o.png",
  "title": "Tilable Dragon Curve",
  "description": "<a href=\"http://en.wikipedia.org/wiki/Dragon_curve\">Dragon Curve</a>.",
  "date": "2013-05-26",
  "tags": "Processing processingorg colour dragoncurve recursion fractal",
  "enabled": true,
},
  {
  "src": "images/b-is-for-bar-chart_8844376577_o.png",
  "title": "B is for Bar Chart",
  "description": "and Breaking Bad.<br>When I finish watching a TV show I like to find out which episodes are highest and lowest rated, then I watch the &quot;best&quot; and &quot;worst&quot; episode. The best episode is often very different to the standard episodes, whilst the worst episode is usually very dull.<br>Buffy the Vampire Slayer is a great example of this. The highest rated episodes are &quot;Hush&quot;, &quot;Once More, with feeling&quot; and &quot;The Body&quot;. The lowest rated episodes are &quot;Where the Wild Things Are&quot; and &quot;Beer Bad&quot;.<br>The screenshot shows Breaking Bad, because this show is unusual in that the trendline goes up.",
  "date": "2013-05-26",
  "tags": "csharp chart application",
  "enabled": false,
},
  {
  "src": "images/d-is-for-dexter_8846304411_o.png",
  "title": "D is for Dexter",
  "description": "and Data. Everyone loves data.<br>I wrote this toy to view occurrences of words in TV shows, by analysing the subtitles files.<br>The screenshot shows words from Dexter. I've purposefully chosen generic words to avoid spoilers.",
  "date": "2013-05-26",
  "tags": "colour application csharp chart film_and_tv",
  "enabled": false,
},
  {
  "src": "images/c-is-for-cesaro-curve_8846797518_o.png",
  "title": "Cesaro Curve",
  "description": "",
  "date": "2013-05-26",
  "tags": "Processing processingorg colour recursion cesaro_curve fractal",
  "enabled": true,
},
  {
  "src": "images/a-is-for-angles_8752535984_o.png",
  "title": "Angular Maze",
  "description": "",
  "date": "2013-05-19",
  "tags": "maze black_and_white random Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/spiral-maze_8730255464_o.png",
  "title": "Spiral Maze",
  "description": "The maze layout is generated in C# and then it is rendered by Processing.",
  "date": "2013-05-12",
  "tags": "csharp Processing processingorg maze black_and_white spiral random",
  "enabled": true,
},
  {
  "src": "images/ulam-spiral-mod-82_8686065725_o.jpg",
  "title": "Ulam Spiral mod 82",
  "description": "",
  "date": "2013-04-27",
  "tags": "Processing processingorg black_and_white ulam_spiral",
  "enabled": true,
},
  {
  "src": "images/ulam-spiral---primes-and-composites_8686102941_o.png",
  "title": "Ulam Spiral - Primes and Composites",
  "description": "Primes are displayed in red.<br>Composites are displayed in white, proportional to the amount of divisors that they have.",
  "date": "2013-04-27",
  "tags": "Processing processingorg ulam_spiral prime composite",
  "enabled": true,
},
  {
  "src": "images/gapminder-style-chart_8476753373_o.png",
  "title": "Gapminder-style Chart",
  "description": "I made a Processing sketch that creates Gapminder-style charts.<br>Data sources: <a href=\"http://www.gapminder.org/data/documentation/gd005/\">Child Mortality</a> and <a href=\"http://www.gapminder.org/data/documentation/gd008/\">Children per Woman</a>.",
  "date": "2013-02-16",
  "tags": "Processing processingorg chart colour",
  "enabled": true,
},
  {
  "src": "images/dragon-curve_8377509042_o.png",
  "title": "Dragon Curve",
  "description": "<a href=\"http://en.wikipedia.org/wiki/Dragon_curve\">Dragon Curve</a>.",
  "date": "2013-01-13",
  "tags": "Processing processingorg colour dragon_curve recursion fractal",
  "enabled": true,
},
  {
  "src": "images/visualising-merge-sort-2_8235541959_o.png",
  "title": "Visualising Merge Sort #2",
  "description": "I wanted to try visualising merge sort with more readable items and using curves to display the way each element is moved.<br>As before, the first row contains the initial set of colours and then each row shows the array after the subsets have been sorted.<br><a href=\"http://en.wikipedia.org/wiki/Merge_sort\">Merge Sort</a>.",
  "date": "2012-12-02",
  "tags": "Processing processingorg random colour mergesort",
  "enabled": true,
},
  {
  "src": "images/visualising-merge-sort-1_8235692086_o.png",
  "title": "Visualising Merge Sort #1",
  "description": "The first row contains the initial array of colours.<br>Each row after is the result of sorting each subset, until the final row, where everything is sorted.<br><a href=\"http://en.wikipedia.org/wiki/Merge_sort\">Merge Sort</a>.",
  "date": "2012-12-01",
  "tags": "Processing processingorg mergesort random black_and_white",
  "enabled": true,
},
  {
  "src": "images/numbers_8194565996_o.png",
  "title": "Numbers",
  "description": "I've written a lot of code to generate number sets, but I've never used them together. So I made this.<br>This sketch allows you to select sets of numbers (prime numbers, happy numbers, etc) and then they will be highlighted on the right.<br>The squares on the right represent the numbers 1 to 10,000 and they are coloured based on the amount of sets that they belong to. Blue numbers belong to fewer sets and red numbers belong to more sets.<br>Based on my arbitrary number sets, the most interesting numbers (from 1 to 10,000) are:<br>1st: 1<br>2nd: 3<br>3rd: 2, 5, 7<br>4th: 6, 12, 210, 378, 1212, 2556<br>5th: 8, 9, 11, 21, 23, 31, 36, 120, 132, 666, 888, 1122, 1128, 1332, 1818, 2628, 4248, 4428, 5112, 8118, 8880<br>The lowest of the least interesting numbers is 106.",
  "date": "2012-11-17",
  "tags": "Processing processingorg vb csharp colour numbers",
  "enabled": false,
},
  {
  "src": "images/hexagons_8186923230_o.png",
  "title": "Hexagons",
  "description": "I liked <a href=\"http://www.flickr.com/photos/davebollinger/6104417094/in/photostream/\">&quot;D20110725B (lo)&quot; by davebollinger</a>, so I made a Processing sketch to randomly generate similar results.",
  "date": "2012-11-14",
  "tags": "Processing processingorg recursion hexagons random black_and_white fractal",
  "enabled": true,
},
  {
  "src": "images/moon_8180485882_o.png",
  "title": "Moon",
  "description": "Wanted to see if I could recreate &quot;Density Crescent 1&quot; by davebollinger:<br><a href=\"http://www.flickr.com/photos/davebollinger/2087264829/in/photostream\">www.flickr.com/photos/davebollinger/2087264829/in/photost...</a><br>I experimented with making the shapes only appear in a crescent and adding perlin noise to make them look like moons, but both effects looked awful.",
  "date": "2012-11-12",
  "tags": "Processing processingorg moon black_and_white random",
  "enabled": false,
},
  {
  "src": "images/julia-set_8151792225_o.png",
  "title": "Julia set",
  "description": "This is -0.042,-0.6875 of the <a href=\"http://en.wikipedia.org/wiki/Julia_set\">Julia set</a>.",
  "date": "2012-11-03",
  "tags": "julia colour Processing processingorg fractal",
  "enabled": true,
},
  {
  "src": "images/diffusion-limited-aggregation_8129512814_o.png",
  "title": "Diffusion-limited Aggregation",
  "description": "<a href=\"http://en.wikipedia.org/wiki/Diffusion-limited_aggregation\">Diffusion-limited Aggregation</a>.",
  "date": "2012-10-28",
  "tags": "Processing processingorg diffusion_limited_aggregation colour random",
  "enabled": true,
},
  {
  "src": "images/how-many-squares-are-there_8109523935_o.png",
  "title": "How many squares are there?",
  "description": "ericsurf6 asked the question in this video:<br><a href=\"http://www.youtube.com/watch?v=Q-kBv3S0dWM\">www.youtube.com/watch?v=Q-kBv3S0dWM</a><br>Data was collected from comments that were a number or an answer like &quot;32 squares&quot;. This was about 71% of the comments at the time.<br>This picture looks nicer in the full size view:<br><a href=\"http://www.flickr.com/photos/_robson_/8109523935/sizes/l/in/photostream/#allsizes-photo\">www.flickr.com/photos/_robson_/8109523935/sizes/l/in/phot...</a>",
  "date": "2012-10-21",
  "tags": "Processing processingorg ericsurf6 text chart",
  "enabled": false,
},
  {
  "src": "images/buildings_8068775525_o.png",
  "title": "Buildings",
  "description": "I searched for nine famous buildings via Google image search, then I combined the returned images to produce the result above.<br>Many buildings were rejected, because they don't have a single iconic view. For example, the Bank of China, Statue of Liberty, Sydney Opera House, Sphinx, Big Ben, World Trade Center and the Shanghai World Financial Center.<br>Buildings displayed are: Arc de Triomphe, France. Collosseum, Italy. Disney Castle, Japan. Eiffel Tower, France. Gherkin, England. Pyramid of Giza, Egypt. Petronas Towers, Malaysia. Tower Bridge, England. Taj Mahal, India.",
  "date": "2012-10-09",
  "tags": "Processing processingorg image collage buildings",
  "enabled": true,
},
  {
  "src": "images/flower-power_8068095840_o.png",
  "title": "Flower Power",
  "description": "",
  "date": "2012-10-08",
  "tags": "Processing processingorg random",
  "enabled": false,
},
  {
  "src": "images/a-lot-of-bottle_8060766255_o.png",
  "title": "Bottles",
  "description": "",
  "date": "2012-10-06",
  "tags": "Processing processingorg random",
  "enabled": true,
},
  {
  "src": "images/usa-statistics_8040602704_o.png",
  "title": "USA Statistics",
  "description": "All data sourced from Wikipedia:<br><a href=\"http://en.wikipedia.org/wiki/Template:USStateLists\">en.wikipedia.org/wiki/Template:USStateLists</a><br>Edit in 2020: There used to be a link to the interactive Java version of this, but nobody uses Java any more, so I've deleted the link.",
  "date": "2012-09-30",
  "tags": "Processing svg colour map interactive chart text processingorg",
  "enabled": false,
},
  {
  "src": "images/rorschach-inkblot-generator_8040690943_o.png",
  "title": "Rorschach Inkblots",
  "description": "A Processing sketch that generates <a href=\"http://en.wikipedia.org/wiki/Rorschach_test\">Rorschach inkblots</a>.",
  "date": "2012-09-30",
  "tags": "Processing random interactive processingorg black_and_white",
  "enabled": true,
},
  {
  "src": "images/highest-mountains_8000927326_o.png",
  "title": "Highest Mountains",
  "description": "I made an interactive sketch showing details about the highest mountains.<br>Edit in 2020: I've removed the link, because it was built in Java and nobody uses that nowadays!",
  "date": "2012-09-18",
  "tags": "Processing processingorg chart highest_mountains interactive text",
  "enabled": false,
},
  {
  "src": "images/patersons-worms_7980941691_o.png",
  "title": "Paterson's Worms",
  "description": "This is <a href=\"http://en.wikipedia.org/wiki/Paterson's_worms\">Paterson's worm</a> 1,5,0,5,1,1,1 at termination.",
  "date": "2012-09-13",
  "tags": "Processing processingorg colour paterson's_worms recursion",
  "enabled": true,
},
  {
  "src": "images/famous-five---before--after_7977938436_o.png",
  "title": "Famous Five - Before & After",
  "description": "This is the most frequently appearing words before and after the five main characters from all of the Famous Five books.<br>Horizontal distance represents the number of times that character is mentioned in the books. Vertical distance represents the frequency of that word.<br>Common words (and, asked, etc) are excluded. Words only count as before/after if they appear in the same sentence. This takes into account variations of names (tim, timmy, timothy, etc).<br>This was created in three steps:<br>1. Obtain and clean up all 21 books.<br>2. Write a C# application to determine all of the frequencies.<br>3. Write a Processing sketch to display the results.",
  "date": "2012-09-12",
  "tags": "Processing processingorg csharp famous_five colour text chart",
  "enabled": true,
},
  {
  "src": "images/rotation_7963526878_o.png",
  "title": "Rotation",
  "description": "I improved my wordle generator so that it can do rotation and only place characters in specified areas.",
  "date": "2012-09-09",
  "tags": "Processing processingorg random text black_and_white",
  "enabled": true,
},
  {
  "src": "images/heatmap_7964809818_o.png",
  "title": "Heatmap",
  "description": "Experimenting with heatmaps. The red dots on the left are the original clicks and this is converted to the image on the right.<br>Clock image is courtesy of sivvus and is in the public domain.<br><a href=\"http://openclipart.org/detail/27002\">openclipart.org/detail/27002</a>",
  "date": "2012-09-09",
  "tags": "Processing processingorg heatmap image colour",
  "enabled": false,
},
  {
  "src": "images/bingo-card-generator_7932189018_o.png",
  "title": "Bingo Card Generator",
  "description": "This forward-thinking sketch dynamically takes a digital subset of items and amalgamates them into this user-focussed bingo card. My only mission-critical requirement was to keep it absent of colour.<br>CNN (an outside-the-box and environmentally-conscience company) say that the word &quot;creative&quot; was the most overused buzzword of 2011.",
  "date": "2012-09-04",
  "tags": "Processing processingorg bingo random text buzzword buzzword_bingo black_and_white",
  "enabled": false,
},
// {{{1,2,1},,{0,8,1},},,{{1,1,0},,{0,1,0},},}, at step 10529<br>{{{1,2,1},,{1,1,0},},,{{1,1,0},,{0,1,1},},}, at step 46533<br>{{{1,2,1},,{1,2,0},},,{{0,1,0},,{0,1,0},},}, at step 824936<br>{{{1,2,1},,{1,2,1},},,{{1,8,1},,{0,2,0},},}, at step 3837<br>{{{1,2,1},,{1,8,1},},,{{1,2,1},,{0,2,0},},}, at step 43578<br><br><br>{{{1,8,0},,{0,1,1},},,{{0,8,0},,{0,8,1},},}, at step 303406<br>{{{1,8,0},,{1,2,1},},,{{0,2,0},,{0,8,1},},}, at step 659754<br>{{{1,8,0},,{1,2,1},},,{{0,2,1},,{1,8,0},},}, at step 50250<br>{{{1,8,1},,{0,1,0},},,{{1,1,0},,{1,2,0},},}, at step 10221<br>{{{1,8,1},,{0,2,0},},,{{0,8,0},,{0,8,0},},}, at step 22381<br><br><br>{{{1,8,1},,{0,8,0},},,{{1,1,0},,{0,1,0},},}, at step 42914<br>{{{1,8,1},,{0,8,0},},,{{1,2,1},,{1,2,0},},}, at step 25521<br>{{{1,8,1},,{0,8,1},},,{{1,2,1},,{0,8,0},},}, at step 21566<br>{{{1,8,1},,{1,2,0},},,{{0,8,0},,{0,8,0},},}, at step 1507081<br>{{{1,8,1},,{1,2,1},},,{{1,1,0},,{0,1,1},},}, at step 6085<br><br><br>{{{1,8,1},,{1,8,1},},,{{1,2,1},,{0,1,0},},}, at step 7716<br>{{{1,2,1},,{0,4,1},},,{{1,1,0},,{0,8,0},},}, at step 13712<br>{{{1,2,1},,{0,8,1},},,{{1,4,0},,{1,8,0},},}, at step 74602<br>{{{1,4,1},,{1,2,1},},,{{1,8,0},,{1,1,1},},}, at step 6276<br>{{{1,4,1},,{1,8,1},},,{{1,4,0},,{0,1,0},},}
  {
  "src": "images/turmite-2_7924984116_o.png",
  "title": "Turmite #2",
  "description": "I improved my Langton's Ant sketch to become a <a href=\"http://en.wikipedia.org/wiki/Turmite\">Turmite</a> sketch. This is 20 configurations.",
  "date": "2012-09-03",
  "tags": "Processing processingorg turmite black_and_white",
  "enabled": true,
},
// {{{0,1,1},,{0,8,1},},,{{1,2,0},,{0,1,1},},}, at step 9770<br>{{{0,2,1},,{0,1,1},},,{{1,2,1},,{1,8,0},},}, at step 31330<br>{{{0,2,1},,{0,2,1},},,{{1,1,0},,{0,2,1},},}, at step 201449<br>{{{0,2,1},,{0,8,0},},,{{1,8,1},,{0,2,0},},}, at step 7313<br>{{{0,2,1},,{0,8,0},},,{{1,8,1},,{1,1,0},},}, at step 3591<br><br><br>{{{0,2,1},,{1,2,1},},,{{1,8,1},,{1,8,0},},}, at step 18058<br>{{{0,8,1},,{1,2,1},},,{{1,1,0},,{1,1,1},},}, at step 4731<br>{{{0,2,1},,{0,8,1},},,{{1,1,0},,{1,8,1},},}, at step 45423<br>{{{0,8,1},,{1,8,1},},,{{1,2,1},,{0,2,0},},}, at step 15133<br>{{{1,1,1},,{0,1,0},},,{{0,2,0},,{1,8,0},},}, at step 7303<br><br><br>{{{1,1,1},,{0,1,1},},,{{1,2,1},,{0,1,0},},}, at step 23518<br>{{{1,1,1},,{0,2,1},},,{{1,8,0},,{1,2,0},},}, at step 7481<br>{{{1,1,1},,{0,8,1},},,{{1,2,0},,{1,1,1},},}, at step 9262<br>{{{1,1,1},,{1,8,0},},,{{1,2,1},,{0,1,0},},}, at step 21406<br>{{{1,2,0},,{0,8,1},},,{{1,8,0},,{0,1,1},},}, at step 11354<br><br><br>{{{1,2,0},,{0,8,1},},,{{1,8,0},,{0,2,1},},}, at step 152193<br>{{{1,2,0},,{1,2,1},},,{{0,1,0},,{0,1,1},},}, at step 7111<br>{{{1,2,1},,{0,2,0},},,{{0,1,0},,{1,2,1},},}, at step 64315<br>{{{1,2,1},,{0,2,1},},,{{1,1,0},,{1,1,1},},}, at step 25691<br>{{{1,2,1},,{0,8,1},},,{{1,1,0},,{0,1,0},},}, at step 10529
  {
  "src": "images/turmite-1_7924984276_o.png",
  "title": "Turmite #1",
  "description": "I improved my Langton's Ant sketch to become a <a href=\"http://en.wikipedia.org/wiki/Turmite\">Turmite</a> sketch. This is 20 configurations.",
  "date": "2012-09-03",
  "tags": "Processing processingorg turmite black_and_white",
  "enabled": true,
},
  {
  "src": "images/langtons-ants-2_7917055696_o.png",
  "title": "Langton's Ants #2",
  "description": "Some outputs from various configurations of <a href=\"http://en.wikipedia.org/wiki/Langton's_ant\">Langton's Ants</a>.<br>Top left: RLLRRRLRRRR at step 9,701,570.<br>Top right: RRLRLLLRRRR at step 215,278.<br>Bottom left: RRRLRLLRRRRR at step 1,212,765.<br>Bottom right: RLLRRLRRRRR at step 65,663,214.",
  "date": "2012-09-02",
  "tags": "Processing processingorg langton langton's_ant colour",
  "enabled": true,
},
  {
  "src": "images/langtons-ants-1_7917056230_o.png",
  "title": "Langton's Ants #1",
  "description": "Some outputs from various configurations of <a href=\"http://en.wikipedia.org/wiki/Langton's_ant\">Langton's Ants</a>.<br>Top left: RLRRRRLLLRR at step 1,150,242.<br>Top right: RRLL at step 17,064,189.<br>Bottom left: RLRRRRRLL at step 16,87,893.<br>Bottom right: RLLRLLLRRRR at step 38,807,721.",
  "date": "2012-09-02",
  "tags": "Processing processingorg langton langton's_ant colour",
  "enabled": true,
},
  {
  "src": "images/roguelike-dungeon-generator_7890441858_o.png",
  "title": "Roguelike Dungeon Generator",
  "description": "An output from my random dungeon generator.<br>The generator includes special rooms (caves, prisons, mazes), &quot;circular&quot; rooms, tunnel shortening, intersecting tunnels, pathfinding and cellular automata.",
  "date": "2012-08-29",
  "tags": "vb random dungeon_generator roguelike text",
  "enabled": true,
},
  {
  "src": "images/eye-tracking_7882504556_o.png",
  "title": "Eye Tracking",
  "description": "",
  "date": "2012-08-28",
  "tags": "Processing processingorg eyes random",
  "enabled": false,
},
  {
  "src": "images/terrain-combined_7872813222_o.png",
  "title": "Terrain (Combined)",
  "description": "I combined the code from my two terrain generators to make this.",
  "date": "2012-08-27",
  "tags": "Processing processingorg terrain 3d colour perlin_noise perlin random",
  "enabled": true,
},
  {
  "src": "images/sterling_7873708512_o.png",
  "title": "Sterling",
  "description": "My attempt at recreating the painting from Roger Sterling's office in Mad Men.<br><a href=\"http://www.housebeautiful.com/cm/housebeautiful/images/Pg/05-hbx-roger-sterling-office-lgn.jpg\">www.housebeautiful.com/cm/housebeautiful/images/Pg/05-hbx...</a>",
  "date": "2012-08-27",
  "tags": "Processing processingorg mad_men roger_sterling black_and_white film_and_tv",
  "enabled": false,
},
  {
  "src": "images/one-day-of-mouse-movement_7845785662_o.png",
  "title": "One Day of Mouse Movement",
  "description": "I wrote this mouse tracker in C#.<br>Red circles represent left-clicks. Green circles represent right-clicks. Black lines represent the path of the cursor.",
  "date": "2012-08-23",
  "tags": "csharp mouse cursor",
  "enabled": true,
},
  {
  "src": "images/key-press-frequency_7841085108_o.png",
  "title": "Key Press Frequency",
  "description": "I wrote a keylogger in C# and then recorded the keys that I pressed for two days.<br>I then used Processing to make this treemap, which shows the relative frequency.<br>For reference, I pressed the space bar 7,737 times.",
  "date": "2012-08-22",
  "tags": "csharp Processing treemap colour chart processingorg text",
  "enabled": true,
},
  {
  "src": "images/heat-map_7834032138_o.png",
  "title": "Heat Map",
  "description": "Data courtesy of the <a href=\"http://www.metoffice.gov.uk\">Met Office</a>.",
  "date": "2012-08-21",
  "tags": "weather heat_map Processing colour sunlight london processingorg text chart",
  "enabled": true,
},
  {
  "src": "images/treemap_7811745452_o.png",
  "title": "Treemap",
  "description": "Number of gold medals obtained by each country in the London 2012 Olympics.<br>This uses Treemap Java Algorithms created by Ben Bederson and Martin Wattenberg.<br><a href=\"http://www.cs.umd.edu/hcil/treemap-history/\">www.cs.umd.edu/hcil/treemap-history/</a>",
  "date": "2012-08-19",
  "tags": "Processing processingorg colour treemap chart text olympics",
  "enabled": false,
},
  {
  "src": "images/edge-magazine---issue-1-to-247-december-2012_7818246724_o.png",
  "title": "Edge Magazine - Issue 1 to 247 (December 2012)",
  "description": "Edge put all of their magazine covers online, so I made this collage.<br>The covers were downloaded via a simple web scraper in C#, then the collage was generated in Processing.<br><a href=\"http://www.edge-online.com/features/every-edge-magazine-cover-ever\">www.edge-online.com/features/every-edge-magazine-cover-ever</a>",
  "date": "2012-08-19",
  "tags": "Processing image edge_magazine collage edge csharp processingorg",
  "enabled": false,
},
  {
  "src": "images/terrain-diamond-square-algorithm_7809545426_o.png",
  "title": "Terrain (Diamond-square Algorithm)",
  "description": "Another terrain generator, but this one uses the <a href=\"http://en.wikipedia.org/wiki/Diamond-square_algorithm\">diamond-square algorithm</a> and has gradual colouring.",
  "date": "2012-08-18",
  "tags": "diamond-square_algorithm colour random Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/splashscreen_7803874260_o.png",
  "title": "Splashscreen",
  "description": "I made this splashscreen for my game <em>Numbers</em> in the Dragon 32/64 style.<br>Here's a <a href=\"http://www.mobygames.com/game/dragon-3264/cuthbert-goes-walkabout/screenshots/gameShotId,188064/\">real splashscreen from that system</a>.",
  "date": "2012-08-17",
  "tags": "paint text dragon_32 dragon_64 dragon_32/64",
  "enabled": true,
},
  {
  "src": "images/terrain-perlin-noise_7798155394_o.png",
  "title": "Terrain (Perlin Noise)",
  "description": "My first attempt at using 3d graphics in Processing. This is a terrain generator using <a href=\"http://en.wikipedia.org/wiki/Perlin_noise\">Perlin noise</a>.",
  "date": "2012-08-16",
  "tags": "colour random 3d perlin Processing processingorg perlin_noise",
  "enabled": true,
},
  {
  "src": "images/free-eye-test_7789974052_o.png",
  "title": "Eye Test",
  "description": "A test for protanopia, which is a type of colour blindness.",
  "date": "2012-08-15",
  "tags": "random protanopia colourblindness Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/cityscape_7783425478_o.png",
  "title": "Night City",
  "description": "I wrote a Processing sketch that randomly generates a city scene at night. Inspired by this <a href=\"https://www.shutterstock.com/da/image-illustration/retro-cityscape-high-resolution-jpeg-version-84296422\">stock image</a>.",
  "date": "2012-08-14",
  "tags": "random cityscape Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/roots_7783785878_o.png",
  "title": "Roots",
  "description": "Wasn't intended to look so sinister.",
  "date": "2012-08-14",
  "tags": "random colour Processing processingorg black_and_white",
  "enabled": true,
},
  {
  "src": "images/maze-4_7776311898_o.png",
  "title": "Maze #4",
  "description": "A little application that allows the player to move around the maze, whilst viewing it in 2d and &quot;3d&quot;.<br>I only cared about the graphical output, so there's no way to win. You just walk around the maze until you die in real-life.",
  "date": "2012-08-13",
  "tags": "vb maze random colour 3d",
  "enabled": false,
},
  {
  "src": "images/raycasting_7776799582_o.png",
  "title": "Raycasting",
  "description": "I can now make graphics at the level of 1992!<br>I followed this tutorial and then wrote the code in Visual Basic 6. It uses DirectX 8 to render the graphics.<br><a href=\"http://lodev.org/cgtutor/raycasting.html\">lodev.org/cgtutor/raycasting.html</a>",
  "date": "2012-08-13",
  "tags": "vb colour raycasting 3d wolfenstein",
  "enabled": false,
},
  {
  "src": "images/paper-snowflakes_7766684800_o.png",
  "title": "Paper Snowflakes",
  "description": "An output from my Processing sketch that makes paper snowflakes. Structural integrity is not guaranteed.",
  "date": "2012-08-12",
  "tags": "random colour Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/olympic-rings-visualisation_7766685008_o.png",
  "title": "Olympic Rings visualisation",
  "description": "I wanted to make an interactive and more understandable version of this:<br><a href=\"http://oceaniaeuropeamericasafricaasia.tumblr.com/\">oceaniaeuropeamericasafricaasia.tumblr.com/</a>",
  "date": "2012-08-12",
  "tags": "colour maths text olympics Processing processingorg",
  "enabled": false,
},
  {
  "src": "images/maze-3_7766685146_o.png",
  "title": "Maze #3",
  "description": "This sketch generates a maze, then colours the solution in blue.",
  "date": "2012-08-12",
  "tags": "maths colour random maze Processing processingorg",
  "enabled": false,
},
  {
  "src": "images/maze-2_7766685506_o.png",
  "title": "Distance Maze #2",
  "description": "An output from my Processing sketch that generates a maze and colours the solution in red. Every other part of the maze is coloured depending on how close it is to the solution path.<br>This version is biased against straight lines.",
  "date": "2012-08-12",
  "tags": "maths colour random maze Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/maze-1_7766685692_o.png",
  "title": "Distance Maze #1",
  "description": "An output from my Processing sketch that generates a maze and colours the solution in red. Every other part of the maze is coloured depending on how close it is to the solution path.<br>This version is biased towards straight lines.",
  "date": "2012-08-12",
  "tags": "maths colour random maze Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/mandelbrot-2_7766685824_o.png",
  "title": "Mandelbrot #2",
  "description": "<a href=\"http://en.wikipedia.org/wiki/Mandelbrot_set\">Mandelbrot set</a>.",
  "date": "2012-08-12",
  "tags": "random colour mandlebrot Processing processingorg fractal",
  "enabled": true,
},
  {
  "src": "images/mandelbrot-1_7766686272_o.png",
  "title": "Mandelbrot #1",
  "description": "<a href=\"http://en.wikipedia.org/wiki/Mandelbrot_set\">Mandelbrot set</a>.",
  "date": "2012-08-12",
  "tags": "maths colour mandlebrot Processing processingorg fractal",
  "enabled": true,
},
  {
  "src": "images/letter-frequency_7766687070_o.png",
  "title": "Letter Frequency",
  "description": "The relative size of each letter is equal to it's frequency in the English language.",
  "date": "2012-08-12",
  "tags": "text frequency Processing processingorg black_and_white",
  "enabled": false,
},
  {
  "src": "images/optical-illusion-all-the-lines-are-straight_7766687204_o.png",
  "title": "Optical Illusion",
  "description": "All the lines are straight.",
  "date": "2012-08-12",
  "tags": "illusion Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/optical-illusion-this-is-not-a-spiral_7766687350_o.png",
  "title": "Optical Illusion",
  "description": "This is not a spiral.",
  "date": "2012-08-12",
  "tags": "illusion Processing processingorg black_and_white",
  "enabled": true,
},
  {
  "src": "images/optical-illusion-the-inside-circles-are-the-same-size_7766687532_o.png",
  "title": "Optical Illusion",
  "description": "The inside circles are the same size.",
  "date": "2012-08-12",
  "tags": "illusion Processing processingorg black_and_white",
  "enabled": true,
},
  {
  "src": "images/optical-illusion-these-circles-are-not-rotating_7766687718_o.png",
  "title": "Optical Illusion: ",
  "description": "These circles are not rotating.",
  "date": "2012-08-12",
  "tags": "illusion Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/optical-illusion-nothing-is-moving-here_7766688038_o.png",
  "title": "Optical Illusion",
  "description": "Nothing is moving here.",
  "date": "2012-08-12",
  "tags": "illusion colour Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/optical-illusion-squares-a-and-b-are-the-same-colour_7766688276_o.png",
  "title": "Optical Illusion",
  "description": "Squares A and B are the same colour.",
  "date": "2012-08-12",
  "tags": "illusion colour Processing processingorg black_and_white",
  "enabled": true,
},
  {
  "src": "images/optical-illusion-there-are-no-black-dots_7766688418_o.png",
  "title": "Optical Illusion",
  "description": "There are no black dots.",
  "date": "2012-08-12",
  "tags": "illusion colour Processing processingorg black_and_white",
  "enabled": true,
},
  {
  "src": "images/optical-illusion-there-are-no-waves-here_7766688532_o.png",
  "title": "Optical Illusion",
  "description": "There are no waves here.",
  "date": "2012-08-12",
  "tags": "illusion colour Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/optical-illusion-these-bars-are-not-curved_7766688706_o.png",
  "title": "Optical Illusion",
  "description": "These bars are not curved.",
  "date": "2012-08-12",
  "tags": "illusion Processing processingorg black_and_white",
  "enabled": true,
},
  {
  "src": "images/gradients_7766688870_o.png",
  "title": "Gradients",
  "description": "Best avoided.",
  "date": "2012-08-12",
  "tags": "colour gradients Processing processingorg",
  "enabled": false,
},
  {
  "src": "images/approximate-golden-spiral_7766688974_o.png",
  "title": "Golden Spiral",
  "description": "A <a href=\"http://en.wikipedia.org/wiki/Golden_spiral\">golden spiral</a>.",
  "date": "2012-08-12",
  "tags": "maths colour golden_spiral Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/elian-script_7766689240_o.png",
  "title": "Elian Script",
  "description": "This sketch translates letters into Elian Script. For each letter it randomly determines a valid location for the circle and the longer line, if applicable.<br>The third line says &quot;hello world&quot;.<br>Elian Script:<br><a href=\"http://www.ccelian.com/concepca.html\">www.ccelian.com/concepca.html</a>",
  "date": "2012-08-12",
  "tags": "text random elian_script elian Processing processingorg black_and_white",
  "enabled": false,
},
  {
  "src": "images/distance-table_7766689394_o.png",
  "title": "Distance table",
  "description": "This sketch generates a table showing the distances between cities. The input is the name of each city and it's co-ordinates.",
  "date": "2012-08-12",
  "tags": "maths text csharp black_and_white",
  "enabled": false,
},
  {
  "src": "images/colour-wheel_7766689682_o.png",
  "title": "Colour wheel",
  "description": "",
  "date": "2012-08-12",
  "tags": "colour colour_wheel Processing processingorg",
  "enabled": false,
},
  {
  "src": "images/colour-shades_7766690320_o.png",
  "title": "Colour shades",
  "description": "",
  "date": "2012-08-12",
  "tags": "colour Processing processingorg",
  "enabled": false,
},
  {
  "src": "images/clusters_7766690672_o.png",
  "title": "Clusters",
  "description": "This sketch is a work in progress, which I'm hoping to turn into an engine that works in a similar way to this:<br><a href=\"http://visualizing.org/full-screen/41161\">visualizing.org/full-screen/41161</a><br>Currently it handles the creation, resizing and moving of the circles.",
  "date": "2012-08-12",
  "tags": "maths Processing processingorg black_and_white",
  "enabled": false,
},
  {
  "src": "images/vicious-circle_7766691900_o.png",
  "title": "Vicious Circle",
  "description": "This sketch takes an image and then outputs it as circles. Probably not the most useful sketch.",
  "date": "2012-08-12",
  "tags": "image random the_scream Processing processingorg",
  "enabled": false,
},
  {
  "src": "images/racetrack-chart_7766692182_o.png",
  "title": "Racetrack Chart",
  "description": "It's a bar chart, but worse.",
  "date": "2012-08-12",
  "tags": "chart Processing processingorg black_and_white",
  "enabled": false,
},
  {
  "src": "images/foo_7766692464_o.png",
  "title": null,
  "description": "",
  "date": "2012-08-12",
  "tags": "Processing processingorg black_and_white",
  "enabled": true,
},
  {
  "src": "images/olympic-censorship_7766692908_o.png",
  "title": "Olympic Censorship",
  "description": "Don't say these words!<br><a href=\"http://www.tradingstandards.gov.uk/cgi-bin/glos/bus1item.cgi?file=*BADV687-1001.txt\">www.tradingstandards.gov.uk/cgi-bin/glos/bus1item.cgi?fil...</a>",
  "date": "2012-08-12",
  "tags": "random text olympics Processing processingorg black_and_white",
  "enabled": false,
},
  {
  "src": "images/letterle-circle_7766693226_o.png",
  "title": null,
  "description": "",
  "date": "2012-08-12",
  "tags": "random text Processing processingorg black_and_white",
  "enabled": true,
},
  {
  "src": "images/voronoi-taxicab_7766693386_o.png",
  "title": "Voronoi Taxicab",
  "description": "A <a href=\"http://en.wikipedia.org/wiki/Voronoi_diagram\">Voronoi diagram</a> using <a href=\"http://en.wikipedia.org/wiki/Taxicab_geometry\">Taxicab geometry</a>.",
  "date": "2012-08-12",
  "tags": "colour maths random voronoi Processing processingorg black_and_white",
  "enabled": true,
},
  {
  "src": "images/voronoi-circle_7766693508_o.png",
  "title": "Voronoi Circle",
  "description": "A <a href=\"http://en.wikipedia.org/wiki/Voronoi_diagram\">Voronoi diagram</a>.",
  "date": "2012-08-12",
  "tags": "random colour voronoi maths Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/squareception_7766693736_o.png",
  "title": "Squareception",
  "description": "I wanted to see if I could make something like &quot;White Hole&quot; by Graphic Nothing:<br><a href=\"http://www.flickr.com/photos/ilikegraphics/3550394393/in/set-72157623150798499\">www.flickr.com/photos/ilikegraphics/3550394393/in/set-721...</a>",
  "date": "2012-08-12",
  "tags": "squares repetition Processing processingorg black_and_white",
  "enabled": false,
},
  {
  "src": "images/great-balls-of-fire_7766694716_o.png",
  "title": null,
  "description": "",
  "date": "2012-08-12",
  "tags": "colour random Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/random-dot-stereogram-3-layers_7766694888_o.png",
  "title": "Random Dot Stereogram (3 Layers)",
  "description": "Focus your eyes to make each side of the image overlap. A hidden picture will be revealed to you.<br>This is harder to see than the previous picture.",
  "date": "2012-08-12",
  "tags": "stereogram random_dot_stereogram Processing processingorg",
  "enabled": false,
},
  {
  "src": "images/random-dot-stereogram_7766695136_o.png",
  "title": "Random Dot Stereogram",
  "description": "Focus your eyes to make each side of the image overlap. A hidden picture will be revealed to you.",
  "date": "2012-08-12",
  "tags": "random_dot_stereogram stereogram Processing processingorg",
  "enabled": false,
},
  {
  "src": "images/over-the-rainbow_7766695554_o.png",
  "title": "Over the rainbow",
  "description": "",
  "date": "2012-08-12",
  "tags": "colour random stars Processing processingorg",
  "enabled": false,
},
  {
  "src": "images/primewave_7766695926_o.png",
  "title": "PrimeWave",
  "description": "A screenshot of PrimeWave, which is my copy of &quot;El Patron de los Numeros Primos&quot; <a href=\"http://www.jasondavies.com/primos/\">www.jasondavies.com/primos/</a>",
  "date": "2012-08-12",
  "tags": "interactive maths prime Processing processingorg black_and_white",
  "enabled": false,
},
  {
  "src": "images/pills-here_7766696100_o.png",
  "title": "Pills",
  "description": "An output from my Processing sketch that randomly generates images in the style of <a href=\"http://www.flickr.com/photos/ilikegraphics/3642920898/in/set-72157622441241872\\\">&quot;Drugs Work&quot; by Graphic Nothing</a>.",
  "date": "2012-08-12",
  "tags": "random pills Processing processingorg",
  "enabled": true,
},
  {
  "src": "images/random-pattern-generator_7766696364_o.png",
  "title": "Random pattern generator",
  "description": "",
  "date": "2012-08-12",
  "tags": "colour random Processing processingorg",
  "enabled": false,
},
  {
  "src": "images/istanbul-not-constantinople_7767783214_o.png",
  "title": "Istanbul (Not Constantinople)",
  "description": "The lyrics to the song <a href=\"https://en.wikipedia.org/wiki/Istanbul_(Not_Constantinople)\">Istanbul (Not Constantinople)</a> with the two prominent words highlighted.",
  "date": "2012-08-12",
  "tags": "colour text istanbul_(not_constantinople) csharp",
  "enabled": true,
},
  {
  "src": "images/mondrian_7767904608_o.png",
  "title": "Mondrian",
  "description": "An output from my random <a href=\"http://en.wikipedia.org/wiki/Piet_Mondrian\">Mondrian</a>-style generator. The &quot;image&quot; is output to Excel, as cells and borders.",
  "date": "2012-08-12",
  "tags": "colour random vb piet_mondrian excel",
  "enabled": true,
}
];